# Site wide configuration

title: Mario Nikolaus
locale: en_US
description: Mario Nikolaus is a freelance developer.
search: true
share-url: "mnikolaus.github.io"


permalink: /blog/:categories/:year/:title/
paginate_path: "/blog/page:num/"
markdown:    kramdown
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-paginate

redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]

mathjax: true

# paginate: 10

# Octopress

# Default extensions
post_ext: md
page_ext: html

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true