# Site wide configuration

title: Mario Nikolaus - freelance front-end developer
locale: en_US
description: Front-end developer, freelance photographer, technology enthusiast and QA beginner.
search: true
share-url: "http://mnikolaus.me"
image: "http://mnikolaus.me/assets/images/mn.jpg"
image_height: 1000
image_width: 1500



permalink: /blog/:categories/:year/:title/
paginate_path: "/blog/page:num/"
markdown:    kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-paginate

sass:
  style: compressed


mathjax: true

paginate: 10

# Default extensions
post_ext: md
page_ext: html

# Found in _templates/
post_layout: post
page_layout: page

titlecase: true