# Site wide configuration

title: Mario Nikolaus
locale: en_US
description: Mario Nikolaus is a freelance developer.
search: true
share-url: "http://mnikolaus.me"


permalink: /blog/:categories/:year/:title/
paginate_path: "/blog/page:num/"
markdown:    kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-paginate


mathjax: true

paginate: 10

# Default extensions
post_ext: md
page_ext: html

# Found in _templates/
post_layout: post
page_layout: page

titlecase: true